### ISSUE TITLE
cam.Cleanup() Turns off light But Can't get instance again. 

### ISSUE THREAD

**Issue by uastephen45** [techyian/MMALSharp#122]
When i run cam.Cleanup(); i can no longer use the camera even if i run cam = MMALCamera.Instance;

I have to start my app up again. 

how can i turn off the camera and then turn it on again once a client is trying to view the feed?

**Comment by techyian** [comment]
Hi, this is by design. The call to `MMALCamera.Instance` initialises the `MMALCamera` class lazily so it will only initialise when you first call it. The call to `cam.Cleanup()` will unload the Broadcom library and disposes of any unmanaged resources still in use - it should only be called when you don't want to do anything else with the camera. If the issue is seeing the LED on your camera then you can turn it off completely with the following config change in `/boot/config.txt`:

`disable_camera_led=1`
