### ISSUE TITLE
Question: What projects do you use MMALSharp for?

### ISSUE THREAD

**Issue by techyian** [techyian/MMALSharp#41]
Curious to find out how people are using the library and to get feedback :)

**Comment by daniel-lerch** [comment]
I am trying out MMALSharp because I want to take pictures with a RPi Cam and look for QR Codes. The first library I found therefore was [RaspberryIO](https://github.com/unosquare/raspberryio). But even as I included capturing with signal mode, it still took over 700 ms to take a picture in still mode. My first test with MMALSharp took 500 ms and I have the opportunity of a preview port.
